### ISSUE TITLE
Smallest items in the menu missing

### ISSUE THREAD

**Issue by kjvbrt** [HSF/root_cern-To_gltf-Exporter#7]
Smallest items in the Phoenix menu are not show properly:

![image](https://user-images.githubusercontent.com/34742917/176702690-f027acae-e7f4-44d9-b6f8-ed04f98809d2.png)

Using following conversion script: https://gist.github.com/kjvbrt/4e974a35d9cb71750f9e140bb8ab88c1

**Comment by sponce** [comment]
I'm copying here the comment made on the given snippet and I'll close this Issue

> Just to write down what I said verbally : I believe this is just due to the fact that your phoenix is not fully up to date and you are rediscovering https://github.com/HSF/phoenix/issues/426 which has been fixed via https://github.com/HSF/phoenix/pull/456 on June 12th
